trigger:
- Preproduction

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build
  displayName: 'npm build'

- task: CopyFiles@2
  displayName: 'Copy npm package'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/dist'
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1    
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.ArtifactStagingDirectory)'

- task: FtpUpload@2
  inputs:
    credentialsOption: 'inputs'
    serverUrl: 'ftp://ftp.alfirdaws.be'
    username: 'TechExtensor2'
    password: 'Tech2022@'
    rootDirectory: '$(build.ArtifactStagingDirectory)'
    filePatterns: '**'
    remoteDirectory: '/managertest/'
    clean: false
    cleanContents: false
    preservePaths: false
    trustSSL: false