trigger:
- Preproduction

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build
  displayName: 'npm install and build'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
  inputs:
    SourceFolder: '$(agent.builddirectory)/dist/fuse'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
  
- task: PublishBuildArtifacts@1    
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.ArtifactStagingDirectory)'

